[package]
name = "rusty_duckling"
version = "0.1.0"
authors = ["Michal Dyrek <butozerca@gmail.com>", 
           "Mateusz Twaróg <rusty_duckling@mateusztwarog.com>"]

[dependencies]
regex = { path = "deps/regex" }
text_io = { path = "deps/rust-si" }